import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
  }

  class MyApp extends StatelessWidget {
    const MyApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  title: 'Flutter Testing App',
                        theme: ThemeData(primarySwatch: Colors.blue),
                              home: const MyHomePage(title: 'My Testing Project'),
                                  );
                                    }
                                    }

                                    class MyHomePage extends StatefulWidget {
                                      const MyHomePage({super.key, required this.title});
                                        final String title;

                                          @override
                                            State<MyHomePage> createState() => _MyHomePageState();
                                            }

                                            class _MyHomePageState extends State<MyHomePage> {
                                              int _counter = 0;
                                                final List<String> _todos = [];
                                                  final TextEditingController _controller = TextEditingController();

                                                    void _incrementCounter() {
                                                        setState(() {
                                                              _counter++;
                                                                  });
                                                                    }

                                                                      void _addTodo() {
                                                                          if (_controller.text.isNotEmpty) {
                                                                                setState(() {
                                                                                        _todos.add(_controller.text);
                                                                                                _controller.clear();
                                                                                                      });
                                                                                                          }
                                                                                                            }

                                                                                                              @override
                                                                                                                Widget build(BuildContext context) {
                                                                                                                    return Scaffold(
                                                                                                                          appBar: AppBar(title: Text(widget.title)),
                                                                                                                                body: Padding(
                                                                                                                                        padding: const EdgeInsets.all(16.0),
                                                                                                                                                child: Column(
                                                                                                                                                          children: [
                                                                                                                                                                      // Counter Test Section
                                                                                                                                                                                  Card(
                                                                                                                                                                                                child: Padding(
                                                                                                                                                                                                                padding: const EdgeInsets.all(16.0),
                                                                                                                                                                                                                                child: Column(
                                                                                                                                                                                                                                                  children: [
                                                                                                                                                                                                                                                                      Text('Counter Test: $_counter', style: const TextStyle(fontSize: 28, fontWeight: FontWeight.bold)),
                                                                                                                                                                                                                                                                                          const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                              ElevatedButton(
                                                                                                                                                                                                                                                                                                                                    onPressed: _incrementCounter,
                                                                                                                                                                                                                                                                                                                                                          child: const Text('Increment Counter (Test Button)'),
                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 30),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Todo List Test Section
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            controller: _controller,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          labelText: 'Add Todo (Test Input)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onPressed: _addTodo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: const Text('Add to List'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Expanded(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: ListView.builder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          itemCount: _todos.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          itemBuilder: (context, index) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title: Text(_todos[index]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    trailing: IconButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          icon: const Icon(Icons.delete, color: Colors.red),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setState(() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  _todos.removeAt(index);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              floatingActionButton: FloatingActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPressed: _incrementCounter,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: const Icon(Icons.add),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }